project:
  type: website
  output-dir: docs
  
website:
  title: "Official Jared Jimenez-Jenkins Webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/jaredjimenezjenkins/Webpage
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Jared Jimenez-Jenkins"

format:
  html:
    theme: cerulean
    toc: true

editor: source

